#!/bin/bash

# Requirements
# `go get github.com/alecthomas/gometalinter`
# gometalinter --install

set -e

hash gometalinter 2>/dev/null || 
	{ echo >&2 "gometalinter is not installed."; exit 1; }

go get ./...
go test -v -cover .
gometalinter
offers-finder
